<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 -t -s -u static/models/effegibi-forniture-kit/ofv25.glb -r /room/
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  import { type ExtraRoomObjectProps } from '../types';
	import { base } from '$app/paths';
  import { MeshStandardMaterial } from 'three';

  const debugMaterial = new MeshStandardMaterial({ color: 'hotpink' });

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } & ExtraRoomObjectProps = $props()

  const suspend = useSuspense()

  type GLTFResult = {
    nodes: {
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_1']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_2']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_3']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_4']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_5']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_6']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_7']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_8']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_9']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_10']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_11']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_12']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_13']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_14']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_15']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_16']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_17']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_18']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_19']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_20']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_21']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_22']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_23']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_24']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_25']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_26']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_27']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_28']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_29']: THREE.Mesh
      ['OFV25-00621_REV1_-_Vista_3D_-_{3D}_30']: THREE.Mesh
    }
    materials: {
      ['Grigio_1.001']: THREE.MeshStandardMaterial
      ['MATERIAL_NOT_DEFINED.001']: THREE.MeshStandardMaterial
      ['Gres_laminato,_bianco_opaco']: THREE.MeshStandardMaterial
      ['Plastica,_grigia']: THREE.MeshStandardMaterial
      ['Tek.001']: THREE.MeshStandardMaterial
      Bianco: THREE.MeshStandardMaterial
      Rivestimento: THREE.MeshStandardMaterial
      EPS: THREE.MeshStandardMaterial
      Silicone: THREE.MeshStandardMaterial
      ['Vetro_Float_Trasparente.001']: THREE.MeshStandardMaterial
      ALLUMINIO_BIANCO: THREE.MeshStandardMaterial
      ['ACCIAIO.001']: THREE.MeshStandardMaterial
      VETRO_EXTRACHIARO: THREE.MeshStandardMaterial
      Attacchi: THREE.MeshStandardMaterial
      Acciaio_2: THREE.MeshStandardMaterial
      Acciaio_4: THREE.MeshStandardMaterial
      Acciaio_3: THREE.MeshStandardMaterial
      Acciaio_6: THREE.MeshStandardMaterial
      Acciaio_5: THREE.MeshStandardMaterial
      Acciaio_1: THREE.MeshStandardMaterial
      ['Grigio.001']: THREE.MeshStandardMaterial
      ['INTONACO_GRIGIO.001']: THREE.MeshStandardMaterial
      ['Plastica.001']: THREE.MeshStandardMaterial
      Moodlight: THREE.MeshStandardMaterial
      Grigio_Scuro: THREE.MeshStandardMaterial
      ['Nero.001']: THREE.MeshStandardMaterial
      ['Materiale___RGBA_0.569_0.569_0.569_1.001']: THREE.MeshStandardMaterial
      ['Materiale___RGBA_0.898_0.000_0.000_1.000']: THREE.MeshStandardMaterial
      ['Materiale___RGBA_0.898_0.898_0.000_1.000']: THREE.MeshStandardMaterial
      ['Materiale___RGBA_0.639_0.667_0.686_1.000']: THREE.MeshStandardMaterial
    }
  }

  const gltf = suspend(useGltf<GLTFResult>(base + '/models/effegibi-forniture-kit/ofv25.glb'))
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_1'].geometry}
        material={gltf.materials['Grigio_1.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_2'].geometry}
        material={gltf.materials['MATERIAL_NOT_DEFINED.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_3'].geometry}
        material={gltf.materials['Gres_laminato,_bianco_opaco']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_4'].geometry}
        material={gltf.materials['Plastica,_grigia']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_5'].geometry}
        material={gltf.materials['Tek.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_6'].geometry}
        material={gltf.materials.Bianco}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_7'].geometry}
        material={gltf.materials.Rivestimento}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_8'].geometry}
        material={gltf.materials.EPS}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_9'].geometry}
        material={gltf.materials.Silicone}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_10'].geometry}
        material={gltf.materials['Vetro_Float_Trasparente.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_11'].geometry}
        material={gltf.materials.ALLUMINIO_BIANCO}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_12'].geometry}
        material={gltf.materials['ACCIAIO.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_13'].geometry}
        material={gltf.materials.VETRO_EXTRACHIARO}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_14'].geometry}
        material={gltf.materials.Attacchi}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_15'].geometry}
        material={gltf.materials.Acciaio_2}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_16'].geometry}
        material={gltf.materials.Acciaio_4}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_17'].geometry}
        material={gltf.materials.Acciaio_3}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_18'].geometry}
        material={gltf.materials.Acciaio_6}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_19'].geometry}
        material={gltf.materials.Acciaio_5}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_20'].geometry}
        material={gltf.materials.Acciaio_1}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_21'].geometry}
        material={gltf.materials['Grigio.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_22'].geometry}
        material={gltf.materials['INTONACO_GRIGIO.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_23'].geometry}
        material={gltf.materials['Plastica.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_24'].geometry}
        material={gltf.materials.Moodlight}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_25'].geometry}
        material={gltf.materials.Grigio_Scuro}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_26'].geometry}
        material={gltf.materials['Nero.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_27'].geometry}
        material={gltf.materials['Materiale___RGBA_0.569_0.569_0.569_1.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_28'].geometry}
        material={gltf.materials['Materiale___RGBA_0.898_0.000_0.000_1.000']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_29'].geometry}
        material={gltf.materials['Materiale___RGBA_0.898_0.898_0.000_1.000']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['OFV25-00621_REV1_-_Vista_3D_-_{3D}_30'].geometry}
        material={gltf.materials['Materiale___RGBA_0.639_0.667_0.686_1.000']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
