<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/bedBunk.glb -t -s
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { base } from '$app/paths';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		colors?: (number | string)[];
		opacity?: number;
	} = $props();

	type GLTFResult = {
		nodes: {
			Mesh_bedBunk: THREE.Mesh;
			Mesh_bedBunk_1: THREE.Mesh;
			Mesh_cover: THREE.Mesh;
			Mesh_cover_1: THREE.Mesh;
			pillowBottom: THREE.Mesh;
			pillowTop: THREE.Mesh;
		};
		materials: {
			wood: THREE.MeshStandardMaterial;
			carpetWhite: THREE.MeshStandardMaterial;
			carpet: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(base + '/models/kenney-furniture-kit/bedBunk.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	<T.Group position={[-0.3, 0, 0.6]}>
		{#await gltf}
			{@render fallback?.()}
		{:then gltf}
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_bedBunk.geometry}
				material={gltf.materials.wood.clone()}
				material.color={colors?.[0] ?? gltf.materials.wood.color}
				material.opacity={opacity ?? gltf.materials.wood.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_bedBunk_1.geometry}
				material={gltf.materials.carpetWhite.clone()}
				material.color={colors?.[1] ?? gltf.materials.carpetWhite.color}
				material.opacity={opacity ?? gltf.materials.carpetWhite.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Group position={[-0.38, 0.2, -0.83]} rotation={[0, -Math.PI / 2, 0]} scale={0.5}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_cover.geometry}
					material={gltf.materials.carpet.clone()}
					material.color={colors?.[2] ?? gltf.materials.carpet.color}
					material.opacity={opacity ?? gltf.materials.carpet.opacity}
					material.transparent={opacity !== undefined}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_cover_1.geometry}
					material={gltf.materials.carpetWhite.clone()}
					material.color={colors?.[1] ?? gltf.materials.carpetWhite.color}
					material.opacity={opacity ?? gltf.materials.carpetWhite.opacity}
					material.transparent={opacity !== undefined}
				/>
			</T.Group>
			<T.Group position={[-0.38, 0.73, -0.83]} rotation={[0, -Math.PI / 2, 0]} scale={0.5}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_cover.geometry}
					material={gltf.materials.carpet.clone()}
					material.color={colors?.[2] ?? gltf.materials.carpet.color}
					material.opacity={opacity ?? gltf.materials.carpet.opacity}
					material.transparent={opacity !== undefined}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_cover_1.geometry}
					material={gltf.materials.carpetWhite.clone()}
					material.color={colors?.[1] ?? gltf.materials.carpetWhite.color}
					material.opacity={opacity ?? gltf.materials.carpetWhite.opacity}
					material.transparent={opacity !== undefined}
				/>
			</T.Group>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.pillowBottom.geometry}
				material={gltf.materials.carpetWhite.clone()}
				material.color={colors?.[1] ?? gltf.materials.carpetWhite.color}
				material.opacity={opacity ?? gltf.materials.carpetWhite.opacity}
				material.transparent={opacity !== undefined}
				position={[0.12, 0.2, -1.07]}
				rotation={[0.13, -Math.PI / 2, 0]}
				scale={[0.5, 0.5, 0.85]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.pillowTop.geometry}
				material={gltf.materials.carpetWhite.clone()}
				material.color={colors?.[1] ?? gltf.materials.carpetWhite.color}
				material.opacity={opacity ?? gltf.materials.carpetWhite.opacity}
				material.transparent={opacity !== undefined}
				position={[0.12, 0.74, -1.07]}
				rotation={[0.13, -Math.PI / 2, 0]}
				scale={[0.5, 0.5, 0.85]}
			/>
		{:catch err}
			{@render error?.({ error: err })}
		{/await}

		{@render children?.({ ref })}
	</T.Group>
</T.Group>
