<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/kenney-furniture-kit/chairDesk.glb -t -s
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useCursor, useGltf } from '@threlte/extras';
	import { base } from '$app/paths';
	import { Spring } from 'svelte/motion';

	const { onPointerEnter, onPointerLeave } = useCursor();
	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		colors?: (number | string)[];
		opacity?: number;
	} = $props();

	type GLTFResult = {
		nodes: {
			['chairDesk(Clone)']: THREE.Mesh;
			Mesh_chair: THREE.Mesh;
			Mesh_chair_1: THREE.Mesh;
		};
		materials: {
			metalMedium: THREE.MeshStandardMaterial;
			carpet: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(base + '/models/kenney-furniture-kit/chairDesk.glb');

	let rotation = new Spring(0, {
		stiffness: 0.1,
		damping: 0.6
	});
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes['chairDesk(Clone)'].geometry}
			material={gltf.materials.metalMedium.clone()}
			material.color={colors?.[0] ?? gltf.materials.metalMedium.color}
			material.opacity={opacity ?? gltf.materials.metalMedium.opacity}
			material.transparent={opacity !== undefined}
			position={[-0.16, 0.0, 0.16]}
		>
			<T.Group position={[0.17, 0.19, -0.16]} rotation={[0, rotation.current, 0]}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_chair.geometry}
					material={gltf.materials.carpet.clone()}
					material.color={colors?.[1] ?? gltf.materials.carpet.color}
					material.opacity={opacity ?? gltf.materials.carpet.opacity}
					material.transparent={opacity !== undefined}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_chair_1.geometry}
					material={gltf.materials.metalMedium.clone()}
					material.color={colors?.[0] ?? gltf.materials.metalMedium.color}
					material.opacity={opacity ?? gltf.materials.metalMedium.opacity}
					material.transparent={opacity !== undefined}
				/>
			</T.Group>
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
