<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/kenney-furniture-kit/kitchenCabinet.glb -t -s
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { base } from '$app/paths';

	let {
		fallback,
		error,
		children,
		colors,
		opacity,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		colors?: (number | string)[];
		opacity?: number;
	} = $props();

	type GLTFResult = {
		nodes: {
			Mesh_kitchenCabinet: THREE.Mesh;
			Mesh_kitchenCabinet_1: THREE.Mesh;
			Mesh_door: THREE.Mesh;
			Mesh_door_1: THREE.Mesh;
			Mesh_door_2: THREE.Mesh;
		};
		materials: {
			metal: THREE.MeshStandardMaterial;
			wood: THREE.MeshStandardMaterial;
			woodDark: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(base + '/models/kenney-furniture-kit/kitchenCabinet.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[-0.23, 0.0, 0.2]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_kitchenCabinet.geometry}
				material={gltf.materials.metal.clone()}
				material.color={colors?.[0] ?? gltf.materials.metal.color}
				material.opacity={opacity ?? gltf.materials.metal.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_kitchenCabinet_1.geometry}
				material={gltf.materials.wood.clone()}
				material.color={colors?.[1] ?? gltf.materials.wood.color}
				material.opacity={opacity ?? gltf.materials.wood.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Group position={[0.03, 0.09, -0.03]}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_door.geometry}
					material={gltf.materials.wood.clone()}
					material.color={colors?.[1] ?? gltf.materials.wood.color}
					material.opacity={opacity ?? gltf.materials.wood.opacity}
					material.transparent={opacity !== undefined}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_door_1.geometry}
					material={gltf.materials.woodDark.clone()}
					material.color={colors?.[2] ?? gltf.materials.woodDark.color}
					material.opacity={opacity ?? gltf.materials.woodDark.opacity}
					material.transparent={opacity !== undefined}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_door_2.geometry}
					material={gltf.materials.metal.clone()}
					material.color={colors?.[0] ?? gltf.materials.metal.color}
					material.opacity={opacity ?? gltf.materials.metal.opacity}
					material.transparent={opacity !== undefined}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
