<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/kenney-furniture-kit/rugRound.glb -t -s
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { base } from '$app/paths';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		colors?: string[];
		opacity?: number;
	} = $props();

	type GLTFResult = {
		nodes: {
			Mesh_rugRound: THREE.Mesh;
			Mesh_rugRound_1: THREE.Mesh;
		};
		materials: {
			carpet: THREE.MeshStandardMaterial;
			carpetDarker: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(base + '/models/kenney-furniture-kit/rugRound.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[-0.45, 0, 0.45]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_rugRound.geometry}
				material={gltf.materials.carpet.clone()}
				material.color={colors?.[0] ?? gltf.materials.carpet.color}
				material.opacity={opacity ?? gltf.materials.carpet.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_rugRound_1.geometry}
				material={gltf.materials.carpetDarker.clone()}
				material.color={colors?.[1] ?? gltf.materials.carpetDarker.color}
				material.opacity={opacity ?? gltf.materials.carpetDarker.opacity}
				material.transparent={opacity !== undefined}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
