<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/kenney-furniture-kit/televisionModern.glb -t -s
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useCursor, useGltf } from '@threlte/extras';
	import { base } from '$app/paths';
	import Youtube from '$lib/room/models/Youtube.svelte';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		videoId,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		colors?: (number | string)[];
		opacity?: number;
		videoId?: string;
	} = $props();

	type GLTFResult = {
		nodes: {
			Mesh_televisionModern: THREE.Mesh;
			Mesh_televisionModern_1: THREE.Mesh;
		};
		materials: {
			metalDark: THREE.MeshStandardMaterial;
			metal: THREE.MeshStandardMaterial;
		};
	};

	let playPause: (() => void) | undefined = $state();

	const { onPointerEnter, onPointerLeave } = useCursor();

	const gltf = useGltf<GLTFResult>(base + '/models/kenney-furniture-kit/televisionModern.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_televisionModern.geometry}
				material={gltf.materials.metalDark.clone()}
				material.color={colors?.[0] ?? gltf.materials.metalDark.color}
				material.opacity={opacity ?? gltf.materials.metalDark.opacity}
				material.transparent={opacity !== undefined}
			/>
			{#if !videoId}
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Mesh_televisionModern_1.geometry}
					material={gltf.materials.metal.clone()}
					material.color={colors?.[1] ?? gltf.materials.metal.color}
					material.opacity={opacity ?? gltf.materials.metal.opacity}
					material.transparent={opacity !== undefined}
				/>
			{:else}
				<Youtube position={[0, 0.26, 0.025]} {videoId} bind:playPause />
			{/if}
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
