<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 -t -s -u models/kaykit-furniture-kit/lamp_desk.glb -r /room/
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	import { type ExtraRoomObjectProps } from '../types';
	import RoomObjectMaterial from '../RoomObjectMaterial.svelte';
	import { base } from '$app/paths';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} & ExtraRoomObjectProps = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Cylinder629: THREE.Mesh;
			Cylinder629_1: THREE.Mesh;
			Cylinder629_2: THREE.Mesh;
		};
		materials: {
			a: THREE.MeshStandardMaterial;
			b: THREE.MeshStandardMaterial;
			c: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>(base + '/models/kaykit-furniture-kit/lamp_desk.glb'));
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group>
			<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cylinder629.geometry}
				><RoomObjectMaterial index={0} {colors} {opacity} /></T.Mesh
			>
			<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cylinder629_1.geometry}
				><RoomObjectMaterial index={1} {colors} {opacity} /></T.Mesh
			>
			<T.Mesh geometry={gltf.nodes.Cylinder629_2.geometry}
				><RoomObjectMaterial
					emissive={colors?.[2]}
					emissiveIntensity={1}
					index={2}
					{colors}
					{opacity}
				/></T.Mesh
			>
			<T.PointLight position={[0, 0.8, 0.45]} color={colors?.[2]} intensity={1} />
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
