<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 -t -s -u models/kaykit-furniture-kit/monitor.glb -r /room/
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useCursor, useGltf, useSuspense } from '@threlte/extras';

	import { type ExtraRoomObjectProps } from '../types';
	import RoomObjectMaterial from '../RoomObjectMaterial.svelte';
	import { base } from '$app/paths';
	import Youtube from '$lib/room/models/Youtube.svelte';
	import { Spring } from 'svelte/motion';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		link,
		image,
		isEditing,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} & ExtraRoomObjectProps = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			Cube18237: THREE.Mesh;
			Cube18237_1: THREE.Mesh;
		};
		materials: {
			a: THREE.MeshStandardMaterial;
			image: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>(base + '/models/kaykit-furniture-kit/monitor.glb'));

	let playPause: (() => void) | undefined = $state();

	const { onPointerEnter, onPointerLeave } = useCursor();

	let scale = new Spring(1.0, {
		stiffness: 0.2,
		damping: 0.3
	});
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group
			onpointerenter={() => {
				scale.target = 1.1;
				onPointerEnter();
			}}
			onpointerleave={() => {
				scale.target = 1.0;
				onPointerLeave();
			}}
			scale={scale.current}
		>
			<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cube18237.geometry}
				><RoomObjectMaterial index={0} {colors} {opacity} /></T.Mesh
			>
			<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cube18237_1.geometry}
				><RoomObjectMaterial colors={['#000000']} index={0} {opacity} /></T.Mesh
			>
			{#if link}
				<Youtube
					onclick={(evt: { stopPropagation: () => void }) => {
						if (isEditing) return;
						evt.stopPropagation();
						playPause?.();
					}}
					position={[0, 0.66, 0.15]}
					rotation.x={-0.175}
					videoId={link}
					size={[270 * 2, 150 * 2]}
					bind:playPause
				/>
			{/if}
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
