<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 -t -s -u models/tiny-treats-bubbly-bathroom/plant.glb
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';
	import { base } from '$app/paths';
	import type { ExtraRoomObjectProps } from '../types';
	import RoomObjectMaterial from '../RoomObjectMaterial.svelte';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} & ExtraRoomObjectProps = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			plant_1: THREE.Mesh;
			plant_2: THREE.Mesh;
		};
		materials: {
			a: THREE.MeshStandardMaterial;
			b: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>(base + '/models/tiny-treats-bubbly-bathroom/plant.glb'));
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh castShadow receiveShadow geometry={gltf.nodes.plant_1.geometry}>
			<RoomObjectMaterial {colors} {opacity} index={0} />
		</T.Mesh>
		<T.Mesh castShadow receiveShadow geometry={gltf.nodes.plant_2.geometry}>
			<RoomObjectMaterial {colors} {opacity} index={1} />
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
