<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/models/kenney-furniture-kit/dryer.glb -t -s
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { base } from '$app/paths';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		colors,
		opacity,
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		colors?: (number | string)[];
		opacity?: number;
	} = $props();

	type GLTFResult = {
		nodes: {
			Mesh_dryer: THREE.Mesh;
			Mesh_dryer_1: THREE.Mesh;
			Mesh_dryer_2: THREE.Mesh;
			dryerDoor: THREE.Mesh;
		};
		materials: {
			metalLight: THREE.MeshStandardMaterial;
			metalMedium: THREE.MeshStandardMaterial;
			metalDark: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(base + '/models/kenney-furniture-kit/dryer.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[-0.2, 0.0, 0.15]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_dryer.geometry}
				material={gltf.materials.metalLight.clone()}
				material.color={colors?.[0] ?? gltf.materials.metalLight.color}
				material.opacity={opacity ?? gltf.materials.metalLight.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_dryer_1.geometry}
				material={gltf.materials.metalMedium.clone()}
				material.color={colors?.[1] ?? gltf.materials.metalMedium.color}
				material.opacity={opacity ?? gltf.materials.metalMedium.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Mesh_dryer_2.geometry}
				material={gltf.materials.metalDark.clone()}
				material.color={colors?.[2] ?? gltf.materials.metalDark.color}
				material.opacity={opacity ?? gltf.materials.metalDark.opacity}
				material.transparent={opacity !== undefined}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.dryerDoor.geometry}
				material={gltf.materials.metalLight.clone()}
				material.color={colors?.[0] ?? gltf.materials.metalLight.color}
				material.opacity={opacity ?? gltf.materials.metalLight.opacity}
				material.transparent={opacity !== undefined}
				position={[0.07, 0.23, 0]}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
